{% set version = "2.0.4" %}

package:
  name: bob.io.matlab
  version: {{ version }}

source:
  fn: bob.io.matlab-{{ version }}.zip
  url: https://pypi.python.org/packages/source/b/bob.io.matlab/bob.io.matlab-{{ version }}.zip
  md5: 089155b2d864a6dca0f30491da0ed4fc

build:
  number: 5
  skip: true  # [win]

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base
  - libmatio
  - pkg-config
  - boost 1.61.*

  run:
  - python
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base
  - libmatio
  - boost 1.61.*

test:
  imports:
  - bob
  - bob.io
  - bob.io.matlab
  commands:
  - nosetests -sv bob.io.matlab
  requires:
  - nose

about:
  home: http://github.com/bioidiap/bob.io.matlab
  license: Modified BSD License (3-clause)
  summary: Enable bob.io.base to handle Matlab(R) files

extra:
  recipe-maintainers:
  - 183amir
